# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM anapsix/alpine-java

# copy jar to docker image
copy dist/SearchEngine.jar
CMD ["java","-jar","SearchEngine.jar"]
